package reporter

import (
	"context"
	"html/template"
	"io"

	"github.com/nandy23/devsecops-cli/internal/domain/model"
	"github.com/nandy23/devsecops-cli/internal/domain/scoring"
)

// HTML renders a self-contained single-file HTML report.
type HTML struct{}

func (HTML) Format() string { return "html" }

type htmlData struct {
	A model.Analysis
	S scoring.Report
}

var htmlTmpl = template.Must(template.New("report").
	Funcs(template.FuncMap{"mul": func(a, b float64) float64 { return a * b }}).
	Parse(`<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>devsec report — {{.A.Repository.Name}}</title>
<style>
 body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:2rem auto;max-width:900px;color:#1b1f24;padding:0 1rem}
 h1{margin-bottom:0} .sub{color:#667} .score{font-size:2.5rem;font-weight:700}
 table{border-collapse:collapse;width:100%;margin:1rem 0}
 th,td{border:1px solid #dfe2e5;padding:.5rem .75rem;text-align:left;font-size:.9rem}
 th{background:#f6f8fa} .badge{padding:.1rem .5rem;border-radius:.4rem;font-size:.8rem;color:#fff}
 .present{background:#1a7f37}.missing{background:#cf222e}.partial{background:#bf8700}
 footer{color:#8b949e;font-size:.8rem;margin-top:2rem}
</style></head><body>
<h1>devsec Security Report</h1>
<p class="sub">{{.A.Repository.Name}} · {{.A.GeneratedAt.Format "2006-01-02 15:04"}}</p>
<p class="score">{{.S.Total}}/100 <span class="sub">{{.S.Maturity}}</span></p>

<h2>Detected Technologies</h2>
<table><tr><th>Kind</th><th>Name</th><th>Confidence</th></tr>
{{range .A.Technologies}}<tr><td>{{.Kind}}</td><td>{{.Name}}</td><td>{{printf "%.0f" (mul .Confidence 100)}}%</td></tr>{{end}}
</table>

<h2>Score Breakdown</h2>
<table><tr><th>Category</th><th>Weight</th><th>Earned</th><th>State</th><th>Reason</th></tr>
{{range .S.Categories}}<tr><td>{{.Category}}</td><td>{{.Weight}}</td><td>{{.Earned}}</td>
<td><span class="badge {{.State}}">{{.State}}</span></td><td>{{.Reason}}</td></tr>{{end}}
</table>

<h2>Recommendations</h2>
{{range .A.Recommendations}}<div><h3>{{.Category}} — {{.Tool}} ({{.Severity}})</h3><p>{{.Rationale}}</p></div>{{else}}<p>No recommendations.</p>{{end}}

<footer>Generated by devsec {{.A.ToolVersion}}</footer>
</body></html>`))

func (HTML) Render(_ context.Context, a model.Analysis, s scoring.Report, w io.Writer) error {
	return htmlTmpl.Execute(w, htmlData{A: a, S: s})
}
