package reporter

import (
	"context"
	"fmt"
	"io"

	"github.com/nandy23/devsecops-cli/internal/domain/model"
	"github.com/nandy23/devsecops-cli/internal/domain/scoring"
)

// Markdown renders a human-friendly report suitable for PR comments.
type Markdown struct{}

func (Markdown) Format() string { return "markdown" }

func (Markdown) Render(_ context.Context, a model.Analysis, s scoring.Report, w io.Writer) error {
	p := func(format string, args ...any) { fmt.Fprintf(w, format, args...) }

	p("# devsec Security Report\n\n")
	p("**Repository:** `%s`  \n", a.Repository.Name)
	p("**Generated:** %s  \n", a.GeneratedAt.Format("2006-01-02 15:04:05"))
	p("**Security Score:** %d/100 — %s\n\n", s.Total, s.Maturity)

	p("## Detected Technologies\n\n")
	if len(a.Technologies) == 0 {
		p("_None detected._\n\n")
	} else {
		p("| Kind | Name | Confidence |\n|------|------|-----------|\n")
		for _, t := range a.Technologies {
			p("| %s | %s | %.0f%% |\n", t.Kind, t.Name, t.Confidence*100)
		}
		p("\n")
	}

	p("## Security Score Breakdown\n\n")
	p("| Category | Weight | Earned | State | Reason |\n|----------|-------:|-------:|-------|--------|\n")
	for _, c := range s.Categories {
		p("| %s | %d | %d | %s | %s |\n", c.Category, c.Weight, c.Earned, c.State, c.Reason)
	}
	p("\n")

	p("## Recommendations\n\n")
	if len(a.Recommendations) == 0 {
		p("_No recommendations._\n\n")
	} else {
		for _, r := range a.Recommendations {
			p("### %s — `%s` (%s)\n\n", r.Category, r.Tool, r.Severity)
			p("%s\n\n", r.Rationale)
			p("- **Stage:** %s\n- **Rules:** %v\n\n", r.Stage, r.Sources)
		}
	}

	if len(a.Scans) > 0 {
		p("## Imported Scan Results\n\n")
		for _, sc := range a.Scans {
			p("### %s — `%s` (%d finding(s))\n\n", sc.Tool, sc.Source, len(sc.Findings))
			for _, f := range sc.Findings {
				p("- **%s** (%s): %s — `%s`\n", f.Category, f.Severity, f.Message, f.Location)
			}
			p("\n")
		}
	}

	if len(a.Connectors) > 0 {
		p("## Enterprise Connectors\n\n")
		for _, cn := range a.Connectors {
			p("### %s — `%s`\n\n", cn.Connector, cn.Project)
			if cn.Status != "" {
				p("- **Quality gate:** %s\n", cn.Status)
			}
			for k, v := range cn.Metrics {
				p("- **%s:** %s\n", k, v)
			}
			if len(cn.Findings) > 0 {
				p("\n%d finding(s):\n", len(cn.Findings))
				for _, f := range cn.Findings {
					p("- **%s** (%s): %s\n", f.Category, f.Severity, f.Message)
				}
			}
			p("\n")
		}
	}

	if len(a.Pipelines) > 0 {
		p("## Pipeline Audit\n\n")
		for _, pa := range a.Pipelines {
			p("### %s — `%s`\n\n", pa.Platform, pa.Path)
			if len(pa.Findings) == 0 {
				p("No issues found.\n\n")
				continue
			}
			for _, f := range pa.Findings {
				p("- **%s** (%s): %s\n", f.Category, f.Severity, f.Message)
			}
			p("\n")
		}
	}
	p("---\n_Generated by devsec %s_\n", a.ToolVersion)
	return nil
}
