// Package configgen generates ready-to-use configuration files for the security
// scanners that fit a detected stack (sonar-project.properties, trivy.yaml,
// .gitleaks.toml, .checkov.yaml, syft.yaml, .hadolint.yaml, .ansible-lint).
// devsec never embeds secrets in these files — tokens/URLs are passed at scan
// time or via environment variables.
package configgen

import (
	"sort"
	"strings"

	"github.com/nandy23/devsecops-cli/internal/domain/model"
)

// Service renders scanner config files from an analysis.
type Service struct{}

// New builds the config generator service.
func New() *Service { return &Service{} }

// generator is a single config-file producer, gated by what was detected.
type generator struct {
	path    string
	applies func(model.Analysis) bool
	render  func(model.Analysis) string
}

// Generate returns the applicable config files as path -> content.
func (s *Service) Generate(a model.Analysis) map[string]string {
	out := map[string]string{}
	for _, g := range builtin() {
		if g.applies(a) {
			out[g.path] = g.render(a)
		}
	}
	return out
}

func builtin() []generator {
	return []generator{
		{"sonar-project.properties", hasLanguage, renderSonar},
		{".gitleaks.toml", always, renderGitleaks},
		{"trivy.yaml", func(a model.Analysis) bool { return hasContainer(a) || hasPackageManager(a) }, renderTrivy},
		{".checkov.yaml", hasIaC, renderCheckov},
		{"syft.yaml", hasContainer, renderSyft},
		{".hadolint.yaml", func(a model.Analysis) bool { return hasTech(a, "Docker") }, renderHadolint},
		{".ansible-lint", func(a model.Analysis) bool { return hasTech(a, "Ansible") }, renderAnsibleLint},
	}
}

// ---- predicates ----

func always(model.Analysis) bool        { return true }
func hasLanguage(a model.Analysis) bool { return a.HasKind(model.KindLanguage) }
func hasContainer(a model.Analysis) bool {
	return a.HasKind(model.KindContainer)
}
func hasPackageManager(a model.Analysis) bool { return a.HasKind(model.KindPackageMgr) }
func hasIaC(a model.Analysis) bool {
	return a.HasKind(model.KindIaC) || a.HasKind(model.KindOrchestrator)
}

func hasTech(a model.Analysis, name string) bool {
	for _, t := range a.Technologies {
		if strings.EqualFold(t.Name, name) {
			return true
		}
	}
	return false
}

func projectKey(a model.Analysis) string {
	if a.Repository.Name != "" {
		return a.Repository.Name
	}
	return "project"
}

// ---- renderers ----

func renderSonar(a model.Analysis) string {
	key := projectKey(a)
	return `# Generated by devsec — SonarQube scanner configuration.
# Provide the server URL and token at scan time (never commit the token):
#   sonar-scanner -Dsonar.host.url=<url> -Dsonar.token=$SONAR_TOKEN
sonar.projectKey=` + key + `
sonar.projectName=` + key + `
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/build/**,**/*.min.js,**/*.test.*,**/*.spec.*
sonar.qualitygate.wait=true
`
}

func renderGitleaks(model.Analysis) string {
	return `# Generated by devsec — gitleaks configuration.
# Extends the default gitleaks ruleset; add [[rules]] or allowlist entries as needed.
title = "devsec gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Global allowlist"
paths = [
  '''(.*?)(node_modules|vendor|dist|build)(/|$)''',
]
`
}

func renderTrivy(model.Analysis) string {
	return `# Generated by devsec — Trivy configuration.
severity:
  - HIGH
  - CRITICAL
scan:
  scanners:
    - vuln
    - secret
    - misconfig
vulnerability:
  ignore-unfixed: true
exit-code: 1
format: table
`
}

func renderCheckov(a model.Analysis) string {
	var fw []string
	if hasTech(a, "Terraform") {
		fw = append(fw, "terraform")
	}
	if a.HasKind(model.KindOrchestrator) || hasTech(a, "Helm") {
		fw = append(fw, "kubernetes")
	}
	if len(fw) == 0 {
		fw = append(fw, "terraform")
	}
	sort.Strings(fw)
	var b strings.Builder
	b.WriteString("# Generated by devsec — Checkov configuration.\n")
	b.WriteString("framework:\n")
	for _, f := range fw {
		b.WriteString("  - " + f + "\n")
	}
	b.WriteString("compact: true\nquiet: true\nsoft-fail: false\n")
	return b.String()
}

func renderSyft(model.Analysis) string {
	return `# Generated by devsec — Syft SBOM configuration.
# Produces both SPDX and CycloneDX SBOM artifacts.
output:
  - "spdx-json=sbom.spdx.json"
  - "cyclonedx-json=sbom.cdx.json"
`
}

func renderHadolint(model.Analysis) string {
	return `# Generated by devsec — hadolint configuration.
failure-threshold: warning
ignored: []
trusted-registries: []
`
}

func renderAnsibleLint(model.Analysis) string {
	return `# Generated by devsec — ansible-lint configuration.
profile: moderate
exclude_paths:
  - .cache/
  - .github/
`
}
